### ISSUE TITLE
List dependencies in requirements.txt

### ISSUE THREAD

**Issue by sverhoeven** [epodium/time_series_generator#10]
To run code several dependencies need to be installed. It would be nice to have a list of those dependencies so they can be installed with `pip install -r requirements.txt`.

I found
```
matplotlib
scipy
sklearn
numpy
pandas
jupyter
pyyaml
mcfly # currently uses version installed on system in different dir
```

**Comment by jspaaks** [comment]
or Pipfile, or setup.py

**Comment by jspaaks** [comment]
Also, I think scipy comes with numpy so doesn't need to be included (or at least not pinned to a version, just let SciPy decide)

**Comment by sverhoeven** [comment]
or [pyproject.toml](https://www.python.org/dev/peps/pep-0518/). 

Numpy is directly imported so it should also directly in the dependency list.

**Comment by eriktks** [comment]
Issue migrated to sequgen/sequgen#4
