### ISSUE TITLE
Consider moving repo

### ISSUE THREAD

**Issue by florian-huber** [epodium/time_series_generator#25]
Should we decide to indeed expand the time series generator (and maybe also an additional benchmarking tool on top), than we could maybe move this to a a new organization. I suggest `timewise` as a name :)
(because it will be largely independent of the epodium project)

**Comment by jspaaks** [comment]
`noisynoise`

**Comment by fdiblen** [comment]
`timewise` is taken. what about `time-wise`?
my alternative is `timegen`

**Comment by florian-huber** [comment]
`noisynoise` seems to be taken, but that might just be you Jurriaan ? 😄 

What about `zeitgenerator` ? (`timegenerator` is also an option)

**Comment by jspaaks** [comment]
> noisynoise seems to be taken, but that might just be you Jurriaan

nope not me. but for both `noisynoise` and `timewise`, I think we need to differentiate between the org name and the tool name. 

org name is not as important as the tool name to me

**Comment by jspaaks** [comment]
`jenny` is an Americanism for generator, may be interesting

**Comment by florian-huber** [comment]
> org name is not as important as the tool name to me

Agree.

**Comment by jspaaks** [comment]
More suggestions for tool names:

1. `makesomenoise`
1. `signalcompositor`

Other languages could also work, like florian's suggestion. Some more options for tool names along those lines:

1. `temporales` (abbreviation of `series temporales` from Spanish)
1. `alzamania` Arabic for temporal, apparently
1. `zeitfolgen` not capitalized, sorry Florian :)

Probably a good idea to check with native speakers before committing to this

**Comment by fdiblen** [comment]
timebender
interstellar

**Comment by sverhoeven** [comment]
I think being multivariate aware might be the distinguishing feature of this library as I did not find that functionality in the alternative libraries. So including a word like `multi` would be nice.

**Comment by eriktks** [comment]
We made a copy of this repo sequgen/sequgen
