### ISSUE TITLE
list of features to help us decide which packages are feasible

### ISSUE THREAD

**Issue by fdiblen** [epodium/time_series_generator#26]
@fdiblen and @jspaaks made this list of features to help us decide which packages are feasible.
 
1. License
1. documentation
1. programming language / community
1. extensibility of signal model
1. extensibility of noise model
1. extensibility of sampling parameter space
1. Evidence of a demand. There are users, maintainers+contributors, dependent packages etc.
1. allows multivariate, interdependent time series
1. allows frequency domain constraints
1. should support the use case of programmatically defining signals

Any comments?
ping @florian-huber @eriktks @sverhoeven

**Comment by sverhoeven** [comment]
Those are useful features in combination with the features listed by @eriktks in #24: 

~~11. Supported signal types~~
~~12. Supported noise types~~
~~13. export functionality~~
~~14. software distribution~~
Points already covered with 3, 4 and 5

**Comment by jspaaks** [comment]
Maybe another point is

15. allow easy composition of signals over channels

**Comment by jspaaks** [comment]
And for the (written) record, points 11 and 12 are superseded by extensibility (4 and 5), 13 and 14 are easy to implement ourselves, so not a deal breaker

**Comment by eriktks** [comment]
16. focus of system: does it deal with other tasks than time series generation
17. other relevant information

**Comment by sverhoeven** [comment]
For point 8 `allows multivariate, interdependent time series` what do we include in being `interdependent` ? 

- Channels created with shared config which slight mutation
- 1 channel can be formed from another channel
- 1 channel can be formed from multiple other channels
- signal generator function produces data for multiple channels
- signal generator function knows which data was in previous time step over all channels

**Comment by eriktks** [comment]
Issue migrated to sequgen/sequgen#18
