### ISSUE TITLE
data for use case: accelerometer

### ISSUE THREAD

**Issue by jspaaks** [epodium/time_series_generator#38]
The accelerometer data from the bird project could be a candidate, data with annotations lives here:

1. https://github.com/NLeSC/eEcology-Classification/blob/1.2.1/data/gull1accelerometerpoints.csv
2. https://github.com/NLeSC/eEcology-Classification/blob/1.2.1/data/gull1annotations.csv
3. https://github.com/NLeSC/eEcology-Classification/blob/1.2.1/data/schemaGull.txt

**Comment by eriktks** [comment]
Issue migrated to sequgen/sequgen#9
